name: deploy osaisen backend
on:
    push:
        branches:
            - main
        paths:
            - apps/backend/src/**
jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: apps/backend
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Wrangler.toml
              run: |
                printf "%s" '${{ secrets.WRANGLER_TOML }}' > wrangler.toml
            
            - name: Check Wrangler.toml
              run: cat wrangler.toml
            
            - name: Setup pnpm 
              uses: pnpm/action-setup@v2
              with:
                  version: 9.0.0
            
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 20
                cache: pnpm
                cache-dependency-path: pnpm-lock.yaml

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Drizzle Generate
              run: pnpm generate
            
            - name: Drizzle Migration
              run: pnpm remote:migration
              env:
                NODE_ENV: production
                CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

            - name: Deploy
              run: pnpm wrangler deploy --minify
              env: 
                NODE_ENV: production
                CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}